# Generated by Django 3.1.7 on 2021-04-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210417_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_resized',
        ),
    ]
