# Generated by Django 3.1.7 on 2021-05-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210506_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend_list',
        ),
    ]
