# Generated by Django 3.1.7 on 2021-05-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_friend_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend_requests',
        ),
    ]
