# Generated by Django 3.1.7 on 2021-03-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_max_buddies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='max_buddies',
            field=models.IntegerField(default=5, verbose_name='Max Buddies'),
        ),
    ]
