# Generated by Django 3.1.7 on 2021-03-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210326_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='max_buddies',
            field=models.IntegerField(choices=[(5, 'Small'), (10, 'Medium'), (20, 'Large')]),
        ),
    ]
