# Generated by Django 3.1.7 on 2021-03-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210326_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_participants',
            field=models.IntegerField(default=0),
        ),
    ]
