# Generated by Django 3.1.7 on 2021-03-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_num_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_participants',
            field=models.IntegerField(default=1),
        ),
    ]
