# Generated by Django 3.1.7 on 2021-04-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20210418_1352'),
        ('post', '0009_auto_20210418_2019'),
    ]

    operations = [
    ]
