# Generated by Django 3.1.7 on 2021-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='postPk',
            field=models.IntegerField(),
        ),
    ]
