# Generated by Django 3.1.7 on 2021-05-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20210426_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='max_buddies',
            field=models.IntegerField(choices=[(5, 'Small 1-5'), (10, 'Medium 1-10'), (20, 'Large 1-20'), (10000, 'Unlimited')]),
        ),
    ]
